(MAINT) Document `Get-DocumentLink`
microsoft/Documentarian pull request #23
Opened 2023-02-02 22:29 UTC by michaeltlombardi

# PR Summary

Prior to this change, the `Get-DocumentLink` function didn't have any reference documentation.

This change:

- Scaffolds the Markdown documentation from the module
- Fills out the reference documentation for `Get-DocumentLink`

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://github.com/michaeltlombardi/DocumentarianModules/blob/main/CONTRIBUTING.md
[style]: https://github.com/michaeltlombardi/DocumentarianModules/blob/main/CONTRIBUTING.md#Style

2023-02-03 13:37 UTC, sdwheeler commented on Source/Modules/Documentarian/Documentation/reference/cmdlets/Get-Document.md
> +online version: 0.0.1
This is a URL for `Get-Help -Online`

2023-02-03 16:30 UTC, sdwheeler commented on Source/Modules/Documentarian/Documentation/reference/cmdlets/Get-Document.md
> +online version: 0.0.1
This is a URL for `Get-Help -Online`

2023-02-03 16:32 UTC, sdwheeler requested changes

2023-02-03 16:32 UTC, sdwheeler commented on Source/Modules/Documentarian/Documentation/reference/cmdlets/Get-DocumentLink.md
> +online version: 0.0.1
This is a URL for `Get-Help -Online`

2023-02-03 16:32 UTC, sdwheeler commented on Source/Modules/Documentarian/Documentation/reference/cmdlets/_index.md
> +Help Version: ''       # unset
These are for updateable help

2023-02-03 20:01 UTC, michaeltlombardi commented on Source/Modules/Documentarian/Documentation/reference/cmdlets/_index.md
> +documents.
I updated these values, but I also removed the module name header. I think we'll need to have a bit of noodling about this for the export-to-maml problem, _but_ we should approach that holistically.

The alternative is to leave the `_index.md` file without this information and keep the `Documentarian.md` file but marked as draft so Hugo never builds it.

2023-02-06 17:57 UTC, michaeltlombardi commented on Source/Modules/Documentarian/Documentation/reference/cmdlets/Get-Document.md
> +```
`````suggestion
```pwsh-syntax
Get-Document
 [[-Path] <String[]>]
 [<CommonParameters>]
```
``````

2023-02-06 18:02 UTC, sdwheeler requested changes

2023-02-06 18:11 UTC, sdwheeler submitted a review, later dismissed
LGTM

2023-02-06 18:46 UTC, merged